name: atproto_dart
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  github: ^9.12.0
  http: ^1.4.0
  lexicon: ^0.2.5
  pubspec: ^2.3.0
  test: ^1.26.2

dev_dependencies:
  lints: ^6.0.0
  melos: ^6.0.0
  import_sorter: ^4.6.0
