name: xrpc
description: Core library for XRPC communication. This is a wrapped HTTP client for AT Protocol.
version: 0.6.1
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/intro
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/xrpc
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.3.0

topics:
  - atproto
  - bluesky
  - http
  - xrpc

dependencies:
  http: ^1.2.1
  nsid: ^0.4.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  mime: ^1.0.5
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  build_runner: ^2.4.8
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  import_sorter: ^4.6.0
