name: atproto_core
description: Core library for clients and tools. This package is mainly used by https://atprotodart.com packages.
version: 0.11.2
homepage: https://atprotodart.com
documentation: https://atprotodart.com/docs/intro
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto_core
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=3.8.0 <4.0.0"

topics:
  - atproto
  - bluesky
  - api
  - core

dependencies:
  xrpc: ^0.6.1
  at_uri: ^0.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  cbor: ^6.2.0
  multiformats: ^0.2.3
  universal_io: ^2.2.2
  atproto_oauth: ^0.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^3.0.6
  import_sorter: ^4.6.0

  atproto_test:
    path: ../atproto_test
