name: at_uri
description: Core library for parsing AT URI in the AT Protocol standard.
version: 0.4.0
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/at_uri
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.8.0

topics:
  - atproto
  - bluesky
  - uri
  - util

dependencies:
  at_identifier: ^0.2.2
  nsid: ^0.4.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  import_sorter: ^4.6.0



screenshots:
  - description: The at_uri package and atproto.dart logo.
    path: screenshots/logo.png
